import type { AppProps } from "next/app";
import { client } from "@/services/QueryClient";
import { QueryClientProvider } from "react-query";
import NextNProgress from "nextjs-progressbar";
import Head from "next/head";

import "@tremor/react/dist/esm/tremor.css";
import "@/styles/globals.css";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<QueryClientProvider client={client}>
				<Component {...pageProps} />
				<NextNProgress color="#7F3DFF" />
			</QueryClientProvider>
		</>
	);
}
